In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [3]:

dataset = pd.read_csv('resultweather.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print(X)
print(y)







[[1 'sunny' 85 85 False]
 [2 'sunny' 80 90 True]
 [3 'overcast' 83 86 False]
 [4 'rainy' 70 96 False]
 [5 'rainy' 68 80 False]
 [6 'rainy' 65 70 True]
 [7 'overcast' 64 65 True]
 [8 'sunny' 72 95 False]
 [9 'sunny' 69 70 False]
 [10 'rainy' 75 80 False]
 [11 'sunny' 75 70 True]
 [12 'overcast' 72 90 True]
 [13 'overcast' 81 75 False]
 [14 'rainy' 71 91 True]]
['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'no']


In [4]:

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 3:4])
X[:, 3:4] = imputer.transform(X[:, 3:4])
print(X)








[[1 'sunny' 85 85.0 False]
 [2 'sunny' 80 90.0 True]
 [3 'overcast' 83 86.0 False]
 [4 'rainy' 70 96.0 False]
 [5 'rainy' 68 80.0 False]
 [6 'rainy' 65 70.0 True]
 [7 'overcast' 64 65.0 True]
 [8 'sunny' 72 95.0 False]
 [9 'sunny' 69 70.0 False]
 [10 'rainy' 75 80.0 False]
 [11 'sunny' 75 70.0 True]
 [12 'overcast' 72 90.0 True]
 [13 'overcast' 81 75.0 False]
 [14 'rainy' 71 91.0 True]]


In [8]:
#encoding dependet
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)






[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[3 'overcast' 83 86.0 False]
 [11 'sunny' 75 70.0 True]
 [5 'rainy' 68 80.0 False]
 [2 'sunny' 80 90.0 True]
 [13 'overcast' 81 75.0 False]
 [1 'sunny' 85 85.0 False]
 [14 'rainy' 71 91.0 True]
 [10 'rainy' 75 80.0 False]
 [9 'sunny' 69 70.0 False]
 [12 'overcast' 72 90.0 True]
 [6 'rainy' 65 70.0 True]]
[[4 'rainy' 70 96.0 False]
 [8 'sunny' 72 95.0 False]
 [7 'overcast' 64 65.0 True]]
[1 1 1 0 1 0 0 1 1 1 0]
[1 0 1]


In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:,3:])
X_test[:, 3:] = sc.transform(X_test[:,3:])
print(X_train)
print(X_train)

[[3 'overcast' 83 0.6711482389101024 -0.9128709291752769]
 [11 'sunny' 75 -1.330921083940374 1.0954451150103321]
 [5 'rainy' 68 -0.07962775715882625 -0.9128709291752769]
 [2 'sunny' 80 1.1716655696227216 1.0954451150103321]
 [13 'overcast' 81 -0.7052744205496001 -0.9128709291752769]
 [1 'sunny' 85 0.5460189062319476 -0.9128709291752769]
 [14 'rainy' 71 1.2967949023008762 1.0954451150103321]
 [10 'rainy' 75 -0.07962775715882625 -0.9128709291752769]
 [9 'sunny' 69 -1.330921083940374 -0.9128709291752769]
 [12 'overcast' 72 1.1716655696227216 1.0954451150103321]
 [6 'rainy' 65 -1.330921083940374 1.0954451150103321]]
[[3 'overcast' 83 0.6711482389101024 -0.9128709291752769]
 [11 'sunny' 75 -1.330921083940374 1.0954451150103321]
 [5 'rainy' 68 -0.07962775715882625 -0.9128709291752769]
 [2 'sunny' 80 1.1716655696227216 1.0954451150103321]
 [13 'overcast' 81 -0.7052744205496001 -0.9128709291752769]
 [1 'sunny' 85 0.5460189062319476 -0.9128709291752769]
 [14 'rainy' 71 1.2967949023008762 1.0954

In [11]:
print(X_test)

[[4 'rainy' 70 1.9224415656916503 -0.9128709291752769]
 [8 'sunny' 72 1.7973122330134954 -0.9128709291752769]
 [7 'overcast' 64 -1.956567747331148 1.0954451150103321]]
